name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force_publish:
        description: Whether to force to publish
        required: true
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created}}

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created || github.event.inputs.force_publish }}
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - run: npm i -g --force corepack
      - run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Generate docs
        run: pnpm doc
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs
          name: docs
      - name: Deploy docs to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: docs
      - name: Build
        run: pnpm run build
      - name: Publish to npm
        run: pnpm publish --access public --no-git-checks
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to JSR
        run: pnpm dlx jsr publish
